/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    archivos: Archivo;
    alergenos: Alergeno;
    categorias: Categoria;
    platos: Plato;
    menus: Menu;
    espacios: Espacio;
    banners: Banner;
    paginas: Pagina;
    experiencias: Experiencia;
    'menus-grupo': MenusGrupo;
    'backup-deltas': BackupDelta;
    'backup-snapshots': BackupSnapshot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    archivos: ArchivosSelect<false> | ArchivosSelect<true>;
    alergenos: AlergenosSelect<false> | AlergenosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    platos: PlatosSelect<false> | PlatosSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    espacios: EspaciosSelect<false> | EspaciosSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    experiencias: ExperienciasSelect<false> | ExperienciasSelect<true>;
    'menus-grupo': MenusGrupoSelect<false> | MenusGrupoSelect<true>;
    'backup-deltas': BackupDeltasSelect<false> | BackupDeltasSelect<true>;
    'backup-snapshots': BackupSnapshotsSelect<false> | BackupSnapshotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'pagina-inicio': PaginaInicio;
    'configuracion-sitio': ConfiguracionSitio;
  };
  globalsSelect: {
    'pagina-inicio': PaginaInicioSelect<false> | PaginaInicioSelect<true>;
    'configuracion-sitio': ConfiguracionSitioSelect<false> | ConfiguracionSitioSelect<true>;
  };
  locale: null;
  user: Usuario & {
    collection: 'usuarios';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos".
 */
export interface Archivo {
  id: number;
  /**
   * Descripción de la imagen para SEO y accesibilidad
   */
  alt?: string | null;
  /**
   * Texto que aparece debajo de la imagen (opcional)
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alergenos".
 */
export interface Alergeno {
  id: number;
  /**
   * Ej: Gluten, Lactosa, Frutos secos, etc.
   */
  nombre: string;
  /**
   * Código corto del alérgeno (ej: G para Gluten)
   */
  codigo: string;
  /**
   * Descripción detallada del alérgeno
   */
  descripcion?: string | null;
  /**
   * Emoji del alérgeno (ej: 🌾) - Fallback si no hay imagen
   */
  icono?: string | null;
  /**
   * Imagen del icono del alérgeno (preferiblemente WebP o SVG)
   */
  imagen?: (number | null) | Archivo;
  /**
   * Número para ordenar los alérgenos
   */
  orden: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  /**
   * Ej: Entrantes, Carnes, Pescados, Postres, etc.
   */
  nombre: string;
  /**
   * URL amigable para la categoría
   */
  slug: string;
  /**
   * Descripción opcional de la categoría
   */
  descripcion?: string | null;
  /**
   * Orden en el que aparece en el menú (1, 2, 3...)
   */
  orden: number;
  /**
   * Desactiva para ocultar la categoría sin borrarla
   */
  activa?: boolean | null;
  /**
   * Imagen representativa (opcional)
   */
  imagen?: (number | null) | Archivo;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platos".
 */
export interface Plato {
  id: number;
  nombre: string;
  /**
   * Descripción del plato e ingredientes principales
   */
  descripcion?: string | null;
  /**
   * Ej: "12,50 €", "60€ Kg.", "Consultar"
   */
  precio: string;
  imagen?: (number | null) | Archivo;
  categoria: number | Categoria;
  /**
   * Selecciona todos los alérgenos que contiene el plato
   */
  alergenos?: (number | Alergeno)[] | null;
  /**
   * Desactiva cuando el plato esté agotado o no disponible
   */
  activo?: boolean | null;
  /**
   * Marca como plato destacado o recomendado
   */
  destacado?: boolean | null;
  /**
   * Orden de aparición dentro de su categoría
   */
  orden?: number | null;
  /**
   * Ej: "Vegano", "Picante", "Recomendado del Chef", etc.
   */
  etiquetas?:
    | {
        etiqueta: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  /**
   * Ej: Menú del Día, Menú Degustación, Menú San Valentín, etc.
   */
  nombre: string;
  /**
   * Pequeño texto decorativo (ej: "Popular", "Exclusivo", "Nuevo")
   */
  etiqueta?: string | null;
  slug: string;
  imagen?: (number | null) | Archivo;
  precio: number;
  /**
   * Ej: "Este menú se ofrece de miércoles a viernes mediodía. A partir de 2 personas."
   */
  descripcion_menu?: string | null;
  /**
   * Texto corto para badge (ej: "Entre semana", "Fines de semana")
   */
  fechasDias?: string | null;
  /**
   * Fecha desde la que está disponible el menú
   */
  fechaInicio?: string | null;
  /**
   * Fecha hasta la que está disponible el menú
   */
  fechaFin?: string | null;
  /**
   * Escribe aquí la composición completa del menú: entrantes, principales, postres, etc.
   */
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * PDF descargable del menú (opcional)
   */
  pdf?: (number | null) | Archivo;
  /**
   * Activa o desactiva la visibilidad del menú
   */
  activo?: boolean | null;
  /**
   * Marca para mostrar en posición destacada
   */
  destacado?: boolean | null;
  orden?: number | null;
  /**
   * Selecciona los días en que está disponible
   */
  diasSemana?: ('lunes' | 'martes' | 'miercoles' | 'jueves' | 'viernes' | 'sabado' | 'domingo')[] | null;
  horario?: ('comidas' | 'cenas' | 'ambos') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "espacios".
 */
export interface Espacio {
  id: number;
  /**
   * Ej: Salón Principal, Zona Bar, Terraza, Sala Privada, etc.
   */
  nombre: string;
  slug: string;
  /**
   * Descripción detallada del espacio
   */
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Múltiples imágenes del espacio
   */
  galeria?:
    | {
        imagen: number | Archivo;
        id?: string | null;
      }[]
    | null;
  /**
   * Número de personas que puede albergar
   */
  capacidad?: number | null;
  /**
   * Ej: "Aire acondicionado", "Vista panorámica", "WiFi", etc.
   */
  caracteristicas?:
    | {
        caracteristica: string;
        id?: string | null;
      }[]
    | null;
  orden: number;
  activo?: boolean | null;
  /**
   * Marca si este espacio se puede reservar para eventos
   */
  disponibleEventos?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  titulo: string;
  /**
   * Texto descriptivo del anuncio
   */
  texto?: string | null;
  imagen?: (number | null) | Archivo;
  link?: {
    url?: string | null;
    texto?: string | null;
    /**
     * Se abrirá en nueva pestaña
     */
    externo?: boolean | null;
  };
  /**
   * Fecha desde la que se muestra el banner
   */
  fechaInicio: string;
  /**
   * Fecha hasta la que se muestra el banner
   */
  fechaFin: string;
  /**
   * Dónde se mostrará el banner
   */
  posicion: 'home-top' | 'home-middle' | 'home-bottom' | 'carta-top' | 'menus-top' | 'global-top';
  /**
   * Tipo de banner para aplicar estilos
   */
  tipo?: ('info' | 'promo' | 'warning' | 'event') | null;
  /**
   * Activa o desactiva el banner manualmente
   */
  activo?: boolean | null;
  /**
   * Orden si hay múltiples banners (mayor número = mayor prioridad)
   */
  prioridad?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  /**
   * Ej: Página de Inicio, Nosotros, etc.
   */
  tituloInterno: string;
  /**
   * Identificador único (nosotros, carta, contacto...)
   */
  slug: string;
  heroImage: number | Archivo;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  imagenEspacio1?: (number | null) | Archivo;
  imagenEspacio2?: (number | null) | Archivo;
  imagenEspacio3?: (number | null) | Archivo;
  imagenEspacio4?: (number | null) | Archivo;
  /**
   * Aparece en la pestaña del navegador y Google
   */
  metaTitle?: string | null;
  /**
   * Breve resumen para los resultados de búsqueda
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiencias".
 */
export interface Experiencia {
  id: number;
  titulo: string;
  slug: string;
  /**
   * Descripción completa de la experiencia
   */
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Descripción breve para la tarjeta
   */
  resumen?: string | null;
  precio: number;
  imagen: number | Archivo;
  /**
   * URL externa para comprar la experiencia
   */
  linkCompra?: string | null;
  /**
   * Color de fondo para la tarjeta (ej: #F5F5DC)
   */
  colorFondo?: string | null;
  /**
   * Lista de cosas que incluye la experiencia
   */
  incluye?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej: "Válido durante 1 año desde la compra"
   */
  validez?: string | null;
  activo?: boolean | null;
  /**
   * Marca para mostrar en posición destacada
   */
  destacado?: boolean | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus-grupo".
 */
export interface MenusGrupo {
  id: number;
  /**
   * Ej: Menús de Empresa, Menús de Celebración, etc.
   */
  nombre: string;
  /**
   * Breve introducción para este conjunto de menús.
   */
  descripcion?: string | null;
  /**
   * Imagen que representará a este grupo de menús.
   */
  imagenPortada?: (number | null) | Archivo;
  /**
   * Selecciona los menús individuales que forman parte de este grupo.
   */
  menus?: (number | Menu)[] | null;
  orden?: number | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-deltas".
 */
export interface BackupDelta {
  id: number;
  collectionSlug: string;
  resourceType: 'collection' | 'global';
  documentId?: string | null;
  operation: 'create' | 'update' | 'delete';
  /**
   * Estado del documento antes del cambio. Null en operaciones de creación.
   */
  previousData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Estado del documento tras el cambio. Null en operaciones de eliminación.
   */
  currentData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array con los nombres de los campos que cambiaron en esta operación.
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  authorId?: string | null;
  authorEmail?: string | null;
  capturedAt: string;
  /**
   * ID del snapshot (backup completo) que incluye este delta.
   */
  snapshotId?: string | null;
  /**
   * SHA-256 del contenido para verificar integridad del delta.
   */
  contentHash?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-snapshots".
 */
export interface BackupSnapshot {
  id: number;
  label: string;
  type: 'full' | 'incremental' | 'weekly' | 'monthly' | 'manual';
  status: 'pending' | 'processing' | 'completed' | 'error' | 'restored';
  /**
   * Número de deltas (cambios individuales) incluidos en este snapshot.
   */
  deltaCount?: number | null;
  /**
   * Array de slugs de colecciones incluidas en este backup.
   */
  collections?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Resumen de documentos por colección: { "platos": 45, "menus": 3, ... }
   */
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sizeBytes?: number | null;
  /**
   * Contenido serializado del backup. Solo para backups almacenados en la BD.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  storageType: 'database' | 'local' | 's3';
  storagePath?: string | null;
  storageUrl?: string | null;
  contentHash?: string | null;
  periodStart?: string | null;
  periodEnd?: string | null;
  triggeredBy?: ('system' | 'admin') | null;
  triggeredByEmail?: string | null;
  errorMessage?: string | null;
  retentionPolicy?: ('normal' | 'weekly' | 'monthly' | 'permanent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'archivos';
        value: number | Archivo;
      } | null)
    | ({
        relationTo: 'alergenos';
        value: number | Alergeno;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'platos';
        value: number | Plato;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'espacios';
        value: number | Espacio;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'experiencias';
        value: number | Experiencia;
      } | null)
    | ({
        relationTo: 'menus-grupo';
        value: number | MenusGrupo;
      } | null)
    | ({
        relationTo: 'backup-deltas';
        value: number | BackupDelta;
      } | null)
    | ({
        relationTo: 'backup-snapshots';
        value: number | BackupSnapshot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos_select".
 */
export interface ArchivosSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alergenos_select".
 */
export interface AlergenosSelect<T extends boolean = true> {
  nombre?: T;
  codigo?: T;
  descripcion?: T;
  icono?: T;
  imagen?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  orden?: T;
  activa?: T;
  imagen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platos_select".
 */
export interface PlatosSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  precio?: T;
  imagen?: T;
  categoria?: T;
  alergenos?: T;
  activo?: T;
  destacado?: T;
  orden?: T;
  etiquetas?:
    | T
    | {
        etiqueta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  nombre?: T;
  etiqueta?: T;
  slug?: T;
  imagen?: T;
  precio?: T;
  descripcion_menu?: T;
  fechasDias?: T;
  fechaInicio?: T;
  fechaFin?: T;
  descripcion?: T;
  pdf?: T;
  activo?: T;
  destacado?: T;
  orden?: T;
  diasSemana?: T;
  horario?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "espacios_select".
 */
export interface EspaciosSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  galeria?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  capacidad?: T;
  caracteristicas?:
    | T
    | {
        caracteristica?: T;
        id?: T;
      };
  orden?: T;
  activo?: T;
  disponibleEventos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  titulo?: T;
  texto?: T;
  imagen?: T;
  link?:
    | T
    | {
        url?: T;
        texto?: T;
        externo?: T;
      };
  fechaInicio?: T;
  fechaFin?: T;
  posicion?: T;
  tipo?: T;
  activo?: T;
  prioridad?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  tituloInterno?: T;
  slug?: T;
  heroImage?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  imagenEspacio1?: T;
  imagenEspacio2?: T;
  imagenEspacio3?: T;
  imagenEspacio4?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiencias_select".
 */
export interface ExperienciasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  resumen?: T;
  precio?: T;
  imagen?: T;
  linkCompra?: T;
  colorFondo?: T;
  incluye?:
    | T
    | {
        item?: T;
        id?: T;
      };
  validez?: T;
  activo?: T;
  destacado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus-grupo_select".
 */
export interface MenusGrupoSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  imagenPortada?: T;
  menus?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-deltas_select".
 */
export interface BackupDeltasSelect<T extends boolean = true> {
  collectionSlug?: T;
  resourceType?: T;
  documentId?: T;
  operation?: T;
  previousData?: T;
  currentData?: T;
  changedFields?: T;
  authorId?: T;
  authorEmail?: T;
  capturedAt?: T;
  snapshotId?: T;
  contentHash?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-snapshots_select".
 */
export interface BackupSnapshotsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  status?: T;
  deltaCount?: T;
  collections?: T;
  stats?: T;
  sizeBytes?: T;
  data?: T;
  storageType?: T;
  storagePath?: T;
  storageUrl?: T;
  contentHash?: T;
  periodStart?: T;
  periodEnd?: T;
  triggeredBy?: T;
  triggeredByEmail?: T;
  errorMessage?: T;
  retentionPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio".
 */
export interface PaginaInicio {
  id: number;
  /**
   * Título principal de la página de inicio
   */
  heroTitle: string;
  /**
   * Subtítulo o claim del restaurante
   */
  heroSubtitle?: string | null;
  heroImage: number | Archivo;
  /**
   * Título de la sección "Sobre nosotros"
   */
  welcomeTitle?: string | null;
  /**
   * Historia y filosofía del restaurante
   */
  welcomeText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Galería de imágenes para la página de inicio
   */
  galeriaInicio?:
    | {
        imagen: number | Archivo;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto del call to action para reservar
   */
  ctaTitle?: string | null;
  ctaText?: string | null;
  /**
   * Texto del botón de reserva
   */
  ctaButtonText?: string | null;
  /**
   * Selecciona 4 imágenes para el fondo de la sección "Regala Gastronomía"
   */
  galeriaRegalo?:
    | {
        imagen: number | Archivo;
        id?: string | null;
      }[]
    | null;
  /**
   * Selecciona los espacios a mostrar en el home
   */
  espaciosDestacados?: (number | Espacio)[] | null;
  /**
   * Selecciona las experiencias a mostrar en el home
   */
  experienciasDestacadas?: (number | Experiencia)[] | null;
  /**
   * Título para SEO (meta title)
   */
  seoTitle?: string | null;
  /**
   * Descripción para SEO (meta description)
   */
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion-sitio".
 */
export interface ConfiguracionSitio {
  id: number;
  /**
   * Nombre oficial del restaurante
   */
  title: string;
  logo?: (number | null) | Archivo;
  /**
   * Descripción breve para SEO y redes sociales
   */
  description?: string | null;
  contact?: {
    phone?: string | null;
    /**
     * Número para recibir reservas por WhatsApp (ej: +34600000000)
     */
    whatsapp?: string | null;
    /**
     * Mensaje que aparecerá al abrir el chat (ej: "Hola, me gustaría reservar una mesa...")
     */
    whatsappMessage?: string | null;
    email?: string | null;
    address?: string | null;
    postalCode?: string | null;
    city?: string | null;
    province?: string | null;
    country?: string | null;
    googleMapsUrl?: string | null;
    coordinates?: {
      lat?: number | null;
      lng?: number | null;
    };
  };
  /**
   * Horarios de apertura del restaurante
   */
  openingHours?:
    | {
        /**
         * Ej: "Lunes a Viernes", "Sábados", etc.
         */
        days?: string | null;
        /**
         * Ej: "13:00 - 16:00 y 20:00 - 23:00"
         */
        hours?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
    tripadvisor?: string | null;
  };
  /**
   * Logos de certificaciones como Sicted, etc.
   */
  footerLogos?:
    | {
        logo: number | Archivo;
        alt: string;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej: © 2026 Restaurante Warynessy. Todos los derechos reservados.
   */
  copyright?: string | null;
  /**
   * ID para el widget de reservas
   */
  coverManagerId?: string | null;
  instagramConfig?: {
    method?: ('api' | 'widget') | null;
    /**
     * Token de acceso de larga duración para la API de Instagram
     */
    apiToken?: string | null;
    /**
     * ID de usuario numérico de Instagram
     */
    apiUserId?: string | null;
    /**
     * Pega aquí el código HTML proporcionado por el servicio de widget (Behold, Elfsight, etc.)
     */
    embedCode?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio_select".
 */
export interface PaginaInicioSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  welcomeTitle?: T;
  welcomeText?: T;
  galeriaInicio?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  ctaButtonText?: T;
  galeriaRegalo?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  espaciosDestacados?: T;
  experienciasDestacadas?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion-sitio_select".
 */
export interface ConfiguracionSitioSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  description?: T;
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        whatsappMessage?: T;
        email?: T;
        address?: T;
        postalCode?: T;
        city?: T;
        province?: T;
        country?: T;
        googleMapsUrl?: T;
        coordinates?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
      };
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        closed?: T;
        id?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        tiktok?: T;
        youtube?: T;
        tripadvisor?: T;
      };
  footerLogos?:
    | T
    | {
        logo?: T;
        alt?: T;
        link?: T;
        id?: T;
      };
  copyright?: T;
  coverManagerId?: T;
  instagramConfig?:
    | T
    | {
        method?: T;
        apiToken?: T;
        apiUserId?: T;
        embedCode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}